[component]
structures = [ "content_blocks" ]
label = "Hero"
description = "Page hero with the heading, description, buttons, and an image"
icon = "wysiwyg"
tags = ["Structure", "Text", "Links"]

[props]
title = "Hi there, we are Imlay Plumbing"
description_html = "<strong>Service</strong> and <strong>Construction</strong> plumbers from Cedar City, Utah."
image = "/images/01.jpg"
image_alt = "Imlay Plumbing's picture"
cta_button = "Get in touch"
cta_button_link = "#contact"
works_button = "See Our Services"
works_button_link = "#services"