[component]
structures = [ "content_blocks" ]
label = "News"
description = "News Section with heading, a image, a description and a link"
icon = "wysiwyg"
tags = ["Content"]

[props]
title = "Recent Works"
description_html = "The latest news, plumbing advice, and tips from Imlay Plumbing"
link_url = "/news"
show_posts = true