[component]
structures = [ "content_blocks" ]
label = "Team Hero"
description = "Team Hero Section with heading, a description and a full width photo"
icon = "wysiwyg"
tags = ["Content"]

[props]
title = "Team Hero"
description_html= "A full width team hero image with a description"
image = "/images/01.jpg"
image_alt = "Imlay Plumbing team photo"
link_url = "/about#team"