[component]
structures = []
label = "Service Card"
description = "Service card used for service lists"
icon = "wysiwyg"
tags = []

[props.service]
title = "Hello World"
subtitle = "Lorem Ipsum"
image = "https://placekitten.com/800/400"
url = "/"