[component]
structures = [ "content_blocks" ]
label = "Team"
description = "Team Section with heading, a description and a link"
icon = "wysiwyg"
tags = ["Content"]

[props]
title = "Team Members"
description_html= "Our team is what sets us apart"
image = "/images/01.jpg"
image_alt = "Imlay Plumbing's team photo"
link_url = "/about#team"
show_team = true