[component]
structures = [ "content_blocks" ]
label = "Team"
description = "Team Section with heading, a description and a link"
icon = "peopleoutline"
tags = ["Content"]

[props]
title = "Team Members"
description_html= ""
show_team = true