[component]
structures = [ "content_blocks" ]
label = "Newsletter Form"
description = "Generic newsletter form"
icon = "wysiwyg"
tags = ["Text"]

[props]
newsletter_title = "Join my mailing list"
newsletter_description = "Get inspiration, updates and, cool stuff!" # Add descriptions to the form.
newsletter_identifier = "plumbing.us14.list-manage.com/subscribe/post?u=300c79bf2443d495f15429a6b&amp;id=e1b830cde8" # Add your MailChimp form identifier.
newsletter_button = "Subscribe"