[component]
structures = [ "content_blocks" ]
label = "Services"
description = "Services Section with heading, a description and a link"
icon = "wysiwyg"
tags = ["Content"]

[props]
title = "Services Offered"
description_html = "No job is too big or too small! When it comes to plumbing we are your one stop shop."
link_url = "/services"
show_services = true