[component]
structures = []
label = "Team Card"
description = "Team card used for team lists"
icon = "people"
tags = []

[props.team-item]
name = "Hello World"
position = "Author"
blurb = "Lorem Ipsum"
image = "https://placekitten.com/1000/600"
